export const favouriteShoes = [
    {
      id: '1',
      name: 'Nike Air Force',
      price: '$367.76',
      image: require('../../../images/hinh3.png'),
      bestSeller: true,
      category: "Men's Shoes",
    },
    {
      id: '2',
      name: 'Nike Air Max',
      price: '$254.89',
      image: require('../../../images/hinh4.png'),
      bestSeller: true,
      category: "Men's Shoes",
    },
    {
      id: '3',
      name: 'Nike Jordan',
      price: '$367.76',
      image: require('../../../images/hinh5.png'),
      bestSeller: true,
      category: "Men's Shoes",
    },
    {
      id: '4',
      name: 'Nike Air Max',
      price: '$254.89',
      image: require('../../../images/hinh6.png'),
      bestSeller: false,
      category: "Men's Shoes",
    },
    {
      id: '5',
      name: 'Nike Air Force',
      price: '$367.76',
      image: require('../../../images/hinh3.png'),
      bestSeller: true,
      category: "Men's Shoes",
    },
    {
      id: '6',
      name: 'Nike Air Max',
      price: '$254.89',
      image: require('../../../images/giay1.png'),
      bestSeller: false,
      category: "Men's Shoes",
    },
    {
      id: '7',
      name: 'Nike Air Jordan',
      price: '$367.76',
      image: require('../../../images/giay2.png'),
      bestSeller: true,
      category: "Men's Shoes",
    },
    {
      id: '8',
      name: 'Nike Air Max',
      price: '$254.89',
      image: require('../../../images/hinh3.png'),
      bestSeller: false,
      category: "Men's Shoes",
    },
  ];