export const mainstack = {
    welcome: 'welcome',
    onboard1: 'onboard_1',
    onboard2: 'onboard_2',
    onboard3: 'onboard_3',
    login: 'login',
    register: 'register',
    recoveryPassword: 'recovery_password',
    main_navigation: 'mainNavigation',
    home: "home",
    passwordauthentication:"passwordauthentication",
    setupnewpassword:"setupnewpassword",
    changpassword:"changpassword",
    shippingaddress:"shippingaddress",
    accountAndSetting: "accountandsetting",
    profile:"profile",
    favorite: "favorite",
    bestSeller: "best_seller",
    bottomnavigation: "bottom_navigation",
    cart: "cart",
    orderHistory: "orderHistory",
    search: "search",
    notification: "notification",
}